### ISSUE TITLE
Ubuntu 14.04 gtk-css window decorations port needed

### ISSUE THREAD

**Issue by JaySeeJC** [numixproject/numix-gtk-theme#101]
I would like to request that the current metacity/xfwm decorations be ported to gtk-css. It does not look very complex and I would even volunteer my time if requested to get this done. Documentation on the theming can be found here https://wiki.ubuntu.com/Unity/Theming

**Comment by satya164** [comment]
Support for the Unity window decorations were added in 495f33647a62d174b1ee2071d81f73c253c0036d

**Comment by JaySeeJC** [comment]
OK i hate sounding like a total noob but i can't for the life of me figure out how to switch the window decorations. neither unity-tweak-tool or ubuntu-tweak are much help. Anyone know how?

**Comment by satya164** [comment]
It is in the GTK3 theme, so you shouldn't need to choose it separately.

**Comment by JaySeeJC** [comment]
Unfortunately it's not. Hopefully it's just a bug that'll be fixed by the time 14.04 goes live, otherwise this might just be the thing that kicks me off unity.

**Comment by satya164** [comment]
@hotice can you assist on this issue?

**Comment by hotice** [comment]
Hmmm in my Ubuntu 14.04 test, you don't need to change the window decorations any more. Now when you change the GTK theme, the window decorations change too. If the window decorations don't change, it's because the theme doesn't support the new Unity decorations (even so, some fallback is used for some themes but not for all, I don't know why exactly).
