### ISSUE TITLE
[LIGHT] Numix is not stylizing some apps

### ISSUE THREAD

**Issue by dgeorgiev** [numixproject/numix-gtk-theme#133]
Hi there,

I want to report that the numix light theme is not properly stylizing some apps

I use the latest update (Georgi send it to me trough email) and when I select it the image viewer (i think some other apps will do the same) is looking like this 

http://i.imgur.com/8imjKJ7.png

PS: When selected radiance (because is light) the image viewer is looking like it should.

**Comment by satya164** [comment]
It's because its using a dark theme for image viewer, totem etc. (some gtk3 apps can request a dark theme). But Unity wm doesn't support dark themes (mutter does), hence the window decoration is light while the app is dark.

If you don't want the dark theme, please delete the file `gtk-dark.css` from the `gtk-3.0` directory.
