### ISSUE TITLE
File explorer Icons not Showing Properly

### ISSUE THREAD

**Issue by pcriv** [numixproject/numix-gtk-theme#159]
I don't know why the File explorer icons are not showing like on the screenshots of the numix theme.
I'm using ElementaryOS Luna.

![files](https://cloud.githubusercontent.com/assets/1854923/4508049/3a337264-4b12-11e4-8117-a4a5eb12703a.png)

**Comment by satya164** [comment]
@me4oslav ?

**Comment by dirtydancing** [comment]
@pablocrivella I am not entirely sure which file explorer icons you are referring to. Is it the navigation icons on the left hand side or the folder icons on the right hand side? I will address both.

I am approaching this from the right hand side first: This is a matter of the icon size.

Take e.g. Ubuntu 14.10 with Nautilus/Files 3.10.1.

In the standard view, the folder icons are displayed like this (do not worry about the folder design, this is Numix folder style No. 5, not the Numix default folder style):

![files_1](https://cloud.githubusercontent.com/assets/7164227/6286175/fa1ed126-b904-11e4-9d27-fad3b69c51f6.png)

Now on to the list view, as in your screenshot (folder icons already getting smaller, but still the same shape):

![files_2](https://cloud.githubusercontent.com/assets/7164227/6286187/1339aeb0-b905-11e4-80d8-f28339090f67.png)

Finally, with the icon size zoomed out as much as possible. This time, the folder icons have changed in shape and look like in your screenshot, because that is the design of the smallest size (16x16):

![files_3](https://cloud.githubusercontent.com/assets/7164227/6286223/60196ab8-b905-11e4-8fb1-0bcfbb858008.png)

At the same time, this answers your question if you are referring to the navigation icons on the left hand side: In that case, that is a matter of the icons that the file manager of your distribution is displaying. In Ubuntu with Nautilus/Files, these are "symbolic"-named icons (grey, also size 16x16), whereas in your case this looks like the file manager is displaying "regular" icons of the size 16x16 (coloured), which is why the icons in your screenshot are the same on the left hand side and on the right hand side.

In any event, this would not be a matter of the GTK theme, but rather of your distribution & file manager.

**Comment by khurshid-alam** [comment]
Closing this. Feel free to reopen if required.
