### ISSUE TITLE
GTK3 applications get transparent on Debian Jessie (possible regression in commit f3f9d80)

### ISSUE THREAD

**Issue by lbssousa** [numixproject/numix-gtk-theme#257]
I'm using Numix theme on my Debian Jessie installation. After updating Numix to the latest git commit, all my GTK3 apps get totally transparent. Is this proposital (e.g. compatibility break with GTK 3.14)?

The latest working commit for me is d6d5854

**Comment by ghost** [comment]
Just checking; did you follow the compilation instructions (rather than just pulling from or cloning the repo)? If not, just try the steps in <b>Manual installation</b> section.

I'm running Arch Linux + XFCE. The File-roller application had gone fully transparent after the latest commit; installing <code>sass</code> and running <code>make</code> fixed the transparency issue except for the menu item colors (see #250).

**Comment by lbssousa** [comment]
@frisbee00 I've just installed it via `make` as you suggested. Now my transparency problems are gone, but I still have some inconsistencies in some apps (e.g. lightdm-gtk-greeter 2.0.1). I'm suspecting of a compatibility break with GTK 3.14.

**Comment by khurshid-alam** [comment]
This is not reproducible in GTK >= 3.16. Closing.
