### ISSUE TITLE
Software Center Fonts Illegible

### ISSUE THREAD

**Issue by ihashacks** [numixproject/numix-gtk-theme#60]
The font and background for Software Center are two shades of gray that are almost indistinguishable.  I would share a screenshot however it appears that both Shutter and Gnome Screenshot are producing all black images on Saucy (ugh).

Details:

```
% lsb_release -r
Release:    13.10
(fully updated as of 20130821 at 22:00 GTM-8)

% apt-cache show libgtk-3-0 | grep ^Version
Version: 3.8.2-3ubuntu7

% apt-cache show numix-gtk-theme | grep ^Version
Version: 1.9-0-158+201308190718~saucy1
Version: 1.9-0-158+201308190717~saucy1
```

I have noticed this across several versions of Numix GTK, so this is nothing new.  I was hoping after a few releases it would go away.

Let me know if there are any other details I can provide.

**Comment by satya164** [comment]
Can you give a screenshot? I cannot use software center as it always crashes for me.

**Comment by jpmacedosilva** [comment]
I'm not using Ubuntu 13.10, but I think I know what ihashacks means. On my Xubuntu 13.04 the drop down menu with all the PPA/sources I can't see the font (only the icons).
I've attached a screen shot showing that you only see the font when you move the mouse over them... Otherwise you don't see the PPA/sources names!
Hope this helps
![ubuntu sc](https://f.cloud.github.com/assets/5247071/1023090/ba8916b6-0dca-11e3-8aea-1085350ace93.png)
!

Best regards.

**Comment by me4oslav** [comment]
I can confirm this bug.
http://i.imgur.com/9MHE7fq.png
