### ISSUE TITLE
Huge texts

### ISSUE THREAD

**Issue by leoheck** [numixproject/numix-gtk-theme#644]
I don't know if this is an issue with numix-gtk-theme but, some texts in ``albert`` and in ``plank`` are huge. Look:

*Albert*
![image](https://cloud.githubusercontent.com/assets/1277920/22154960/cd63aeb2-df14-11e6-994d-7eddf962bd94.png)

*Plank*
![image](https://cloud.githubusercontent.com/assets/1277920/22155019/0682390c-df15-11e6-95b7-3890add14e8c.png)

**Comment by khurshid-alam** [comment]
I couldn't reproduce this with plank in Zesty (gtk-3.22). Can you check Albert with Adwaita?

**Comment by leoheck** [comment]
The text was reduced a lot in Plank with Ambiance/Radiance. And it is huge with Numix/Arc. Albert looks the same. I don't have Adwaita yet.

![image](https://cloud.githubusercontent.com/assets/1277920/22182896/dc481826-e097-11e6-9408-ecdc39fa2af8.png)

![image](https://cloud.githubusercontent.com/assets/1277920/22182919/48ee9dba-e098-11e6-9dc8-2700c6ada226.png)

**Comment by khurshid-alam** [comment]
@ManuelSchneid3r Can you explain why is this happening? Thanks.

**Comment by ManuelSchneid3r** [comment]
This is not a bug of Numix. @leoheck you have to polish the [theme](https://github.com/albertlauncher/albert/pull/304/files#diff-93c03f169c9531aebc8612c28f6d20a4R13).

Btw when I am writing here, Team Numix may I ask you to provide an official Numix theme for [albert](https://github.com/albertlauncher/albert)?

(I mean a stylesheet for the UI of albert)

**Comment by khurshid-alam** [comment]
No. Not here. This is only gtk+. We have numix-kde maintained here: https://github.com/numixproject/numix-kde-theme. A qt-5 style-sheet can be added there if required. If anyone can open a PR I will look into it.

**Comment by ManuelSchneid3r** [comment]
You got me wrong Albert is an independent keyboard launcher. It uses Qt but it is not related to KDE. The front end is themed using qss (QtStyleSheets), a derivative of css. This themes are neither related to the Gtk nor Qt themes/styles. The fonts in the pictures  are that big because leoheck set it that big in his qss.

**Comment by leoheck** [comment]
Thank you for the explanation @ManuelSchneid3r. It would be nice to have an official numix theme for albert. Unfortunately, I don't know enough about scss/css to help with this. 

@khurshid-alam, plank still has the problem. Do you believe this should be changed by plank developers?

**Comment by khurshid-alam** [comment]
@ManuelSchneid3r Oh. Sorry I thought Albert is a part of KDE (or being shipped as default). But since it is not, it would be better if the app itself carries theme specific style-sheets. We can only support desktop-sessions and styles for some popular default apps. 

@leoheck Please open a new issue regarding plank. Since it is indeed shipped by many popular distro as default we can try fixing theme related issues if it is relevant.
