### ISSUE TITLE
Numix Dark GTK2

### ISSUE THREAD

**Issue by f380cedric** [numixproject/numix-gtk-theme#656]
Hi,

Is there a way to have dark theme for gtk2 or the right gtkrc for it ? There are still some apps like web browser (chromium, firefox (?)), mail client (thunderbird), etc., that use gtk2, breaking the harmony with the rest

Thx :)

**Comment by khurshid-alam** [comment]
No. Gtk2 doesn't  support two separate variant ( light or dark). For app breaking the harmony please open a separate issue citing the problem. 

Thanks.

**Comment by f380cedric** [comment]
Yes, I know that gtk2 cannot do that ^-^ . I was hoping that somebody can publish the gtkrc configuration for dark, such that I can set it as default gtk2 conf. For apps, every apps that are using gtk2 and not gtk3.

**Comment by ghost** [comment]
@f380cedric "The Numix Project releases their dark theme as paid. You can’t (legally) get the Numix dark theme for free. If you donate to the Numix Project, they give you Numix Dark."

https://www.quora.com/How-do-I-use-numix-gtk-dark-theme-after-I-installed-numix-gtk-theme?share=1

**Comment by f380cedric** [comment]
Numix is providing gtk3 dark version for free but not gtk2 version ?

**Comment by ghost** [comment]
Yeah I didn't bother checking their website (ssl certificate was expired actually, boring…) but it kinda makes sense since they're professional designers IIRC.
I did need dark gtk2/gtk3 theme as well so I just made one to go with my i3-wm ricing effort if you wanna check it out:
https://github.com/johnfocker/Gruvbox-Dark-Yellow
It's a liitle time consuming but really easy making one with Oomox, give it a try.
